name: Evaluación
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  ejecutar-evaluacion-automatica:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Reset Environment
      run: |
        rm -rf .pytest_cache
        rm -rf __pycache__
    - name: Evaluación
      id: evaluacion
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 60
        max-score: 10
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EVALUACION_RESULTS: "${{steps.evaluacion.outputs.result}}"
      with:
        runners: evaluacion
